FROM openjdk:17-jdk-alpine
COPY target/auth-service.jar .
EXPOSE 8082
ENV EUREKA_HOST=service-registry
ENTRYPOINT ["java", "-jar", "auth-service.jar"]


ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USER
ARG MYSQL_PASSWORD

ENV MYSQL_HOST=${MYSQL_HOST}
ENV MYSQL_PORT=${MYSQL_PORT}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}